apiVersion: kluctl.io/v1beta1
kind: HelmChart
metadata:
  name: cert-manager
  namespace: cert-manager
spec:
  repo: https://charts.jetstack.io
  chart: cert-manager
  version: v1.13.3  # Update version as needed
  releaseName: cert-manager
  createNamespace: true
  values:
    installCRDs: true
    prometheus:
      enabled: false
