# Trivy Operator component - Local environment values
trivy_operator_enabled: true
install_trivy_operator: true

# Environment
environment: local
environmentType: non-prod
secret_source: gcp

# Docker registry credentials (passed as Kluctl args)
docker_username: "{{ args.docker_username | default('') }}"
docker_password: "{{ args.docker_password | default('') }}"
docker_email: "{{ args.docker_email | default('') }}"
