# Trivy Operator component - Production environment values
trivy_operator_enabled: true

# Environment
environment: production
environmentType: prod
secret_source: gcp

# Docker registry credentials (passed as Kluctl args)
docker_username: "{{ args.docker_username | default('') }}"
docker_password: "{{ args.docker_password | default('') }}"
docker_email: "{{ args.docker_email | default('') }}"
docker_auth: "{% if args.docker_username and args.docker_password %}{{ (args.docker_username + ':' + args.docker_password) | b64encode }}{% endif %}"
