version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/components/frontend/"
    schedule:
      interval: "weekly"
  - package-ecosystem: "pip"
    directory: "/components/backend/"
    schedule:
      interval: "weekly"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
