# Backend component - Production environment values
backend_replicas: 3
backend_tag: 1.0.2-5-gb93c5ba # PRODUCTION_IMAGE_TAG
backend_image_pull_policy: Always

# Environment and secrets
environment: production
environmentType: prod
secret_source: gcp

# Docker registry credentials (passed as Kluctl args)
docker_username: "{{ args.docker_username | default('') }}"
docker_password: "{{ args.docker_password | default('') }}"
docker_email: "{{ args.docker_email | default('') }}"
docker_auth: "{% if args.docker_username and args.docker_password %}{{ (args.docker_username + ':' + args.docker_password) | b64encode }}{% endif %}"
