apiVersion: batch/v1
kind: Job
metadata:
  name: db-migrator
  namespace: microadventures
spec:
  template:
    spec:
      initContainers:
        - name: wait-for-postgres
          image: busybox
          command: ['sh', '-c', 'until nc -z postgres-postgresql.postgres.svc.cluster.local 5432; do echo waiting for postgres; sleep 2; done;']
      containers:
        - name: migrate
          image: hedlaron/microadventures-backend:{{ backend_tag | default("latest") }}
          imagePullPolicy: Always
          command: ["uv", "run", "alembic", "upgrade", "heads"]
          env:
            # PostgreSQL connection (required for migration) - from GCP secrets
            - name: POSTGRESQL_USERNAME
              valueFrom:
                secretKeyRef:
                  name: microadventures-{{ secret_source | default("kind") }}-secrets
                  key: POSTGRES_USER
            - name: POSTGRESQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: microadventures-{{ secret_source | default("kind") }}-secrets
                  key: POSTGRES_PASSWORD
            - name: POSTGRESQL_SERVER
              valueFrom:
                configMapKeyRef:
                  name: backend-config
                  key: POSTGRESQL_SERVER
            - name: POSTGRESQL_PORT
              valueFrom:
                configMapKeyRef:
                  name: backend-config
                  key: POSTGRESQL_PORT
            - name: POSTGRESQL_DATABASE
              valueFrom:
                configMapKeyRef:
                  name: backend-config
                  key: POSTGRESQL_DATABASE
            # Application secrets (required for backend application)
            # - name: DATABASE_URL
            #   valueFrom:
            #     secretKeyRef:
            #       name: microadventures-{{ secret_source | default("kind") }}-secrets
            #       key: DATABASE_URL
            - name: JWT_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: microadventures-{{ secret_source | default("kind") }}-secrets
                  key: JWT_SECRET_KEY
            - name: OPENAI_API_KEY
              valueFrom:
                secretKeyRef:
                  name: microadventures-{{ secret_source | default("kind") }}-secrets
                  key: OPENAI_API_KEY
            # Application config
            - name: DOMAIN
              valueFrom:
                configMapKeyRef:
                  name: backend-config
                  key: DOMAIN
            - name: ENVIRONMENT
              valueFrom:
                configMapKeyRef:
                  name: backend-config
                  key: ENVIRONMENT
      restartPolicy: Never
      imagePullSecrets:
        - name: dockerconfigjson
  backoffLimit: 4
