# ⛔️ DONT PUT SECRET FILES IN VCS
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: backend-database-url
  namespace: microadventures
stringData:
  DATABASE_URL: postgres://microadventures:microadventures@microadventures-postgresql.microadventures.svc.cluster.local:5432/microadventures
  POSTGRESQL_USERNAME: microadventures
  POSTGRESQL_PASSWORD: microadventures
  POSTGRESQL_SERVER: microadventures-postgresql.microadventures.svc.cluster.local
  POSTGRESQL_PORT: "5432"
  POSTGRESQL_DATABASE: microadventures
  OPENAI_API_KEY: "sk-placeholder-key-for-development"
  JWT_SECRET_KEY: "development-secret-key-change-in-production"
  DOMAIN: localhost
  ENVIRONMENT: local
  BACKEND_CORS_ORIGINS: "http://localhost:3000,http://localhost:5173"