version: "3"

tasks: 
  restart-backend:
    desc: "Restart backend deployment to pick up new configuration"
    cmds:
      - "kubectl rollout restart deployment backend -n microadventures"
      - "kubectl rollout status deployment backend -n microadventures"

  logs-backend:
    desc: "View logs from the backend deployment"
    cmds:
      - "kubectl logs -l app=backend -n microadventures --tail=50"

  status-backend:
    desc: "Check backend status"
    cmds:
      - "kubectl get pods -l app=backend -n microadventures"
      - "kubectl get svc backend -n microadventures"

  port-forward-backend:
    desc: "Port forward backend to localhost:8000"
    cmds:
      - "kubectl port-forward service/backend 8000:8000 -n microadventures"