targets:
  - name: kind
    context: kind-kind # Use your actual kind context name here
    args:
      $defaults:
        - k8s/values/kind.yaml

  - name: gcp
    context: gke_microadventures_europe-west3-a_microadventures # Replace with your actual GCP cluster context
    args:
      $defaults:
        - k8s/values/gcp.yaml
