targets:
  - name: kind
    context: kind-kind # Use your actual kind context name here
    args:
      $defaults:
        - values/kind.yaml

  - name: gcp
    context: gcp_cluster_context # Replace with your actual GCP cluster context
    args:
      $defaults:
        - values/gcp.yaml
