# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: check-added-large-files
        exclude: |
            (?x)^(
                k8s/\.helm-charts/.*
            )$
      - id: check-toml
      - id: check-yaml
        args:
          - --unsafe
        exclude: |
            (?x)^(
                k8s/\.helm-charts/.*
            )$
      - id: end-of-file-fixer
        exclude: |
            (?x)^(
                components/frontend/src/client/.*|
                components/backend/app/email-templates/build/.*|
                k8s/\.helm-charts/.*
            )$
      - id: trailing-whitespace
        exclude: |
            (?x)^(
                components/frontend/src/client/.*|
                k8s/\.helm-charts/.*
            )$
      - id: check-case-conflict
      - id: check-merge-conflict
      - id: check-json
      - id: debug-statements
      - id: check-docstring-first
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.12.3
    hooks:
      - id: ruff
        args:
          - --fix
        files: ^components/backend/.*\.py$
      - id: ruff-format
        files: ^components/backend/.*\.py$

# Global exclusions
exclude: |
  (?x)^(
    k8s/\.helm-charts/.*|
    \.git/.*|
    \.venv/.*|
    venv/.*|
    __pycache__/.*|
    \.pytest_cache/.*|
    node_modules/.*|
    dist/.*|
    build/.*|
    \.mypy_cache/.*|
    \.ruff_cache/.*|
    components/backend/alembic/versions/.*\.py$
  )$

ci:
  autofix_commit_msg: 🎨 [pre-commit.ci] Auto format from pre-commit.com hooks
  autoupdate_commit_msg: ⬆ [pre-commit.ci] pre-commit autoupdate
