# Local environment specific overrides
# These override the common values for local development

# Environment specifics
environment: local
environmentType: non-prod
domain: "local-microadventures.aronhedl.com"
ingress_host: "local-microadventures.aronhedl.com"
email: "dev-hedlaron@gmail.com"
use_self_signed_certs: true

# Secret configuration
secret_source: gcp
postgres_secret_name: "microadventures-gcp-secrets"

# For local development, use IfNotPresent to avoid pulling images every time
backend_image_pull_policy: IfNotPresent
frontend_image_pull_policy: IfNotPresent

# Local storage class
postgres_storage_class: "standard"
postgres_metrics_enabled: false

# Security
install_trivy_operator: true

# Docker registry credentials (accessed from environment variables via Kluctl args)
docker_username: "{{ args.docker_username | default('') }}"
docker_password: "{{ args.docker_password | default('') }}"
docker_email: "{{ args.docker_email | default('') }}"
