version: '3'

tasks:
  default:
    desc: "Show frontend deployment tasks"
    cmds:
      - echo "Use task frontend:taskname to run frontend tasks"
      - echo "Available tasks - deploy, status, logs, restart, describe"
      - echo "Example - task frontend:deploy"

  apply-configmap:
    desc: "Apply the frontend ConfigMap"
    cmds:
      - kubectl apply -f ConfigMap.yaml

  apply-deployment:
    desc: "Apply the frontend deployment"
    deps: [apply-configmap]
    cmds:
      - kubectl apply -f Deployment.yaml

  apply-service:
    desc: "Apply the frontend Service"
    cmds:
      - kubectl apply -f Service.yaml

  apply-ingressroute:
    desc: "Apply the frontend IngressRoute"
    cmds:
      - kubectl apply -f IngressRoute.yaml

  status:
    desc: "Check frontend deployment status"
    cmds:
      - kubectl get deployment frontend -n microadventures
      - kubectl get pods -l app=frontend -n microadventures
      - kubectl get svc frontend -n microadventures

  logs:
    desc: "View frontend logs"
    cmds:
      - kubectl logs -l app=frontend -n microadventures --tail=50 -f

  describe:
    desc: "Describe frontend deployment"
    cmds:
      - kubectl describe deployment frontend -n microadventures

  restart:
    desc: "Restart the frontend deployment"
    cmds:
      - kubectl rollout restart deployment/frontend -n microadventures
      - kubectl rollout status deployment/frontend -n microadventures

  deploy:
    desc: "Deploy frontend (ConfigMap + Deployment + Service + IngressRoute)"
    deps: [apply-configmap, apply-deployment, apply-service, apply-ingressroute]
    cmds:
      - echo "Frontend deployment complete!"
      - task: status
