kind: KluctlDeployment
name: trivy-operator

resources:
  - path: trivy-operator-helm.yaml
    when: install_trivy_operator == true
  - path: config-audit-policy.yaml
    when: install_trivy_operator == true
