version: "3"

vars:
  IMAGE_REPO: hedlaron/microadventures-backend
  IMAGE_TAG: foobarbaz

tasks:
  build-container-image:
    desc: Build container image
    cmds:
      - docker build -t {{.IMAGE_REPO}}{{.IMAGE_TAG}} .

  build-container-image-multi-arch:
    desc: Build multi-arch container image
    cmds:
      - |
        docker buildx build \
        --platform linux/amd64,linux/arm64 \
        -t {{.IMAGE_REPO}}:{{.IMAGE_TAG}} \
        --push \
        .

  install:
    desc: install dependencies
    cmds:
      - uv sync

  run:
    desc: Start backend server
    cmds:
      - uv run server.py

  run-local-postgres:
    desc: Start local postgres container
    cmds:
      - docker-compose up -d