apiVersion: v1
kind: Secret
metadata:
  name: git-credentials
  namespace: kluctl-gitops
  labels:
    kluctl.io/tag: git-credentials
type: Opaque
stringData:
  username: "{{ args.github_username }}"
  password: "{{ args.github_pat }}"
