[project]
name = "backend"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "alembic>=1.16.2",
    "fastapi[all]>=0.115.13",
    "pydantic>=2.11.7",
    "sqlmodel>=0.0.24",
]
