targets:
  - name: local
    context: kind-kind
    args: 
      environment: local
      environmentType: non-prod

  - name: production
    context: gke_microadventures_europe-west3-a_microadventures
    args: 
      environment: production
      environmentType: prod

args:
  - name: environment
  - name: environmentType

discriminator: kluctl-{{ target.name }}