targets:
  - name: local
    context: kind-kind
    args: 
      environment: local
      environmentType: non-prod

  - name: production
    context: gke_microadventures_europe-west3-a_microadventures
    args: 
      environment: production
      environmentType: prod

args:
  - name: environment
  - name: environmentType
  # Docker registry args (optional, with empty defaults)
  - name: docker_username
    default: ""
  - name: docker_password
    default: ""
  - name: docker_email
    default: ""

discriminator: kluctl-{{ target.name }}

helmChartsDir: helm-charts