vars: 
  - file: values/{{ args.environment }}.yaml  # Common variables for all deployments

# Ordered list of deployments to process
deployments:
  - include: components/namespaces
  - include: components/secrets-sync
  - include: components

commonLabels:
  app: microadventures
