apiVersion: batch/v1
kind: Job
metadata:
  name: db-migrator
  namespace: microadventures
spec:
  template:
    spec:
      containers:
        - name: migrate
          image: hedlaron/microadventures-backend:{{ get(args, "backend_tag", "latest") }}
          imagePullPolicy: Always
          command: ["uv", "run", "alembic", "upgrade", "heads"]
          env:
            # PostgreSQL connection (required for migration) - from GCP secrets
            - name: POSTGRESQL_USERNAME
              valueFrom:
                secretKeyRef:
                  name: microadventures-gcp-secrets
                  key: POSTGRES_USER
            - name: POSTGRESQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: microadventures-gcp-secrets
                  key: POSTGRES_PASSWORD
            - name: POSTGRESQL_SERVER
              valueFrom:
                configMapKeyRef:
                  name: backend-config
                  key: POSTGRESQL_SERVER
            - name: POSTGRESQL_PORT
              valueFrom:
                configMapKeyRef:
                  name: backend-config
                  key: POSTGRESQL_PORT
            - name: POSTGRESQL_DATABASE
              valueFrom:
                configMapKeyRef:
                  name: backend-config
                  key: POSTGRESQL_DATABASE
            # Application config
            - name: DOMAIN
              valueFrom:
                configMapKeyRef:
                  name: backend-config
                  key: DOMAIN
            - name: ENVIRONMENT
              valueFrom:
                configMapKeyRef:
                  name: backend-config
                  key: ENVIRONMENT
      restartPolicy: Never
      imagePullSecrets:
        - name: dockerconfigjson
  backoffLimit: 4
