apiVersion: kluctl.io/v1beta1
kind: HelmChart
metadata:
  name: postgres
  namespace: postgres
spec:
  repo: https://charts.bitnami.com/bitnami
  chart: postgresql
  version: 13.2.0
  releaseName: postgres
  valuesFiles:
    - postgres-values.yaml
