apiVersion: v1
kind: ServiceAccount
metadata:
  name: docker-secret-sync-sa
  namespace: microadventures
  annotations:
    kluctl.io/hook: pre-deploy
    kluctl.io/hook-weight: "-99"
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: docker-secret-sync-role
  annotations:
    kluctl.io/hook: pre-deploy
    kluctl.io/hook-weight: "-99"
rules:
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["create", "update", "patch", "get", "list"]
- apiGroups: [""]
  resources: ["namespaces"]
  verbs: ["get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: docker-secret-sync-binding
  annotations:
    kluctl.io/hook: pre-deploy
    kluctl.io/hook-weight: "-99"
subjects:
- kind: ServiceAccount
  name: docker-secret-sync-sa
  namespace: microadventures
roleRef:
  kind: ClusterRole
  name: docker-secret-sync-role
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: batch/v1
kind: Job
metadata:
  name: create-docker-registry-secret
  namespace: microadventures
  annotations:
    kluctl.io/hook: pre-deploy
    kluctl.io/hook-weight: "-98"
    kluctl.io/hook-delete-policy: before-hook-creation
spec:
  backoffLimit: 3
  template:
    spec:
      serviceAccountName: docker-secret-sync-sa
      restartPolicy: Never
      containers:
      - name: docker-secret-creator
        image: bitnami/kubectl:latest
        env:
        - name: DOCKER_USERNAME
          value: "{{ args.docker_username | default('') }}"
        - name: DOCKER_PASSWORD
          value: "{{ args.docker_password | default('') }}"
        - name: DOCKER_EMAIL
          value: "{{ args.docker_email | default('') }}"
        command:
        - /bin/sh
        - -c
        - |
          # Ensure Docker registry secret exists for microadventures namespace (REQUIRED for private images)
          SECRET_NAME="microadventures-docker-secret"
          NAMESPACE="microadventures"
          
          echo "Checking if Docker registry secret '$SECRET_NAME' exists..."
          if kubectl get secret "$SECRET_NAME" -n "$NAMESPACE" >/dev/null 2>&1; then
            echo "SUCCESS: Docker registry secret '$SECRET_NAME' already exists"
            echo "Secret is ready for pulling private images (hedlaron/microadventures-*)"
          else
            echo "Docker registry secret '$SECRET_NAME' does not exist, creating..."
            if [ -n "${DOCKER_USERNAME}" ] && [ -n "${DOCKER_PASSWORD}" ] && [ -n "${DOCKER_EMAIL}" ]; then
              echo "Creating Docker registry secret using provided credentials..."
              kubectl create secret docker-registry "$SECRET_NAME" \
                --docker-server=https://index.docker.io/v1/ \
                --docker-username="${DOCKER_USERNAME}" \
                --docker-password="${DOCKER_PASSWORD}" \
                --docker-email="${DOCKER_EMAIL}" \
                --namespace="$NAMESPACE" \
                --dry-run=client -o yaml | kubectl apply -f -
              echo "SUCCESS: Docker registry secret created successfully"
            else
              echo "ERROR: Docker registry secret '$SECRET_NAME' does not exist and no credentials provided"
              echo "Private images (hedlaron/microadventures-*) require Docker Hub authentication"
              echo "Please provide Docker Hub credentials via environment variables:"
              echo "  - DOCKER_USERNAME: Docker Hub username"
              echo "  - DOCKER_PASSWORD: Docker Hub password/token"
              echo "  - DOCKER_EMAIL: Docker Hub email address"
              echo "Or manually create the secret with: kubectl create secret docker-registry $SECRET_NAME ..."
              exit 1
            fi
          fi
