apiVersion: v1
kind: ServiceAccount
metadata:
  name: docker-secret-sync-sa
  namespace: microadventures
  annotations:
    kluctl.io/hook: pre-deploy
    kluctl.io/hook-weight: "-99"
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: docker-secret-sync-role
  annotations:
    kluctl.io/hook: pre-deploy
    kluctl.io/hook-weight: "-99"
rules:
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["create", "update", "patch", "get", "list"]
- apiGroups: [""]
  resources: ["namespaces"]
  verbs: ["get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: docker-secret-sync-binding
  annotations:
    kluctl.io/hook: pre-deploy
    kluctl.io/hook-weight: "-99"
subjects:
- kind: ServiceAccount
  name: docker-secret-sync-sa
  namespace: microadventures
roleRef:
  kind: ClusterRole
  name: docker-secret-sync-role
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: batch/v1
kind: Job
metadata:
  name: create-docker-registry-secret
  namespace: microadventures
  annotations:
    kluctl.io/hook: pre-deploy
    kluctl.io/hook-weight: "-98"
    kluctl.io/hook-delete-policy: before-hook-creation
spec:
  backoffLimit: 3
  template:
    spec:
      serviceAccountName: docker-secret-sync-sa
      restartPolicy: Never
      containers:
      - name: docker-secret-creator
        image: bitnami/kubectl:latest
        env:
        - name: DOCKER_USERNAME
          value: "{{ args.docker_username | default('') }}"
        - name: DOCKER_PASSWORD
          value: "{{ args.docker_password | default('') }}"
        - name: DOCKER_EMAIL
          value: "{{ args.docker_email | default('') }}"
        command:
        - /bin/sh
        - -c
        - |
          # Create Docker registry secret for microadventures namespace (REQUIRED for private images)
          if [ -n "${DOCKER_USERNAME}" ] && [ -n "${DOCKER_PASSWORD}" ] && [ -n "${DOCKER_EMAIL}" ]; then
            echo "Creating Docker registry secret for private image access..."
            kubectl create secret docker-registry microadventures-docker-secret \
              --docker-server=https://index.docker.io/v1/ \
              --docker-username="${DOCKER_USERNAME}" \
              --docker-password="${DOCKER_PASSWORD}" \
              --docker-email="${DOCKER_EMAIL}" \
              --namespace=microadventures \
              --dry-run=client -o yaml | kubectl apply -f -
            echo "Docker registry secret created/updated successfully"
          else
            echo "ERROR: Docker credentials are REQUIRED for private image access"
            echo "Missing required environment variables: DOCKER_USERNAME, DOCKER_PASSWORD, DOCKER_EMAIL"
            echo "Applications use private images (hedlaron/microadventures-*) and will fail to pull without credentials"
            echo "Please provide Docker Hub credentials to enable image pulling from private repositories"
            exit 1
          fi
