deployment:
  enabled: true
service:
  enabled: true
  type: LoadBalancer
ports:
  web:
    port: 8000
    exposedPort: 80
  websecure:
    port: 8443
    exposedPort: 443
ingressRoute:
  dashboard:
    enabled: false
installCRDs: true
