apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: secure-main-prod
  namespace: microadventures
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`microadventures.aronhedl.com`)
      kind: Rule
      services:
        - name: frontend
          port: 80
  tls:
    secretName: microadventures-tls-main-prod
