apiVersion: gitops.kluctl.io/v1beta1
kind: KluctlDeployment
metadata:
  name: gitops
  namespace: kluctl-gitops
spec:
  helmChartsDir: .helm-charts
  interval: 5m
  source:
    git:
      url: https://github.com/hedlaron/microadventures.git
      path: k8s
      ref:
        branch: master
  credentials:
    git:
      - host: github.com
        secretRef:
          name: git-credentials
  target: {{args.cluster_name}}
  args:
    # Map cluster_name to the correct target and provide required arguments
    environment: {{args.cluster_name}}
    environmentType: prod
    docker_username: "{{ args.docker_username | default('') }}"
    docker_password: "{{ args.docker_password | default('') }}"
    docker_email: "{{ args.docker_email | default('') }}"
  context: default
  # let it automatically clean up orphan KluctlDeployment resources
  prune: true
  delete: true