apiVersion: gitops.kluctl.io/v1beta1
kind: KluctlDeployment
metadata:
  name: microadventures
  namespace: kluctl-gitops
spec:
  interval: 5m
  source:
    git:
      url: https://github.com/hedlaron/microadventures.git
      path: k8s
  target: {{production}}
  context: default
  # let it automatically clean up orphan KluctlDeployment resources
  prune: true
  delete: true