"""add_challenge_tables

Revision ID: 43f1f9b7fff1
Revises: 10d99654f6bc
Create Date: 2025-06-26 16:22:46.781401

"""

from collections.abc import Sequence

# revision identifiers, used by Alembic.
revision: str = "43f1f9b7fff1"
down_revision: str | None = "10d99654f6bc"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
