"""add_challenge_tables

Revision ID: 43f1f9b7fff1
Revises: 10d99654f6bc
Create Date: 2025-06-26 16:22:46.781401

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '43f1f9b7fff1'
down_revision: Union[str, None] = '10d99654f6bc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###