"""add image_url and missing fields to adventures

Revision ID: g2h3i4j5k6l7
Revises: f1a2b3c4d5e6
Create Date: 2025-06-26 17:58:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'g2h3i4j5k6l7'
down_revision: Union[str, None] = 'f1a2b3c4d5e6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Add missing fields to adventures table
    op.add_column('adventures', sa.Column('image_url', sa.Text(), nullable=True))
    op.add_column('adventures', sa.Column('itinerary', sa.JSON(), nullable=False, server_default='[]'))
    op.add_column('adventures', sa.Column('route', sa.JSON(), nullable=False, server_default='{}'))
    op.add_column('adventures', sa.Column('weather_forecast', sa.JSON(), nullable=False, server_default='{}'))
    op.add_column('adventures', sa.Column('packing_list', sa.JSON(), nullable=False, server_default='{}'))
    op.add_column('adventures', sa.Column('best_season', sa.String(length=50), nullable=True))
    op.add_column('adventures', sa.Column('accessibility', sa.String(length=100), nullable=True))
    
    # Update best_time to match model (was best_time, should be best_season)
    # First copy data if exists, then drop and recreate
    with op.batch_alter_table('adventures') as batch_op:
        batch_op.drop_column('best_time')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Remove the added fields
    op.drop_column('adventures', 'accessibility')
    op.drop_column('adventures', 'best_season')
    op.drop_column('adventures', 'packing_list')
    op.drop_column('adventures', 'weather_forecast')
    op.drop_column('adventures', 'route')
    op.drop_column('adventures', 'itinerary')
    op.drop_column('adventures', 'image_url')
    
    # Restore best_time column
    op.add_column('adventures', sa.Column('best_time', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###
