"""Add public sharing fields to adventures

Revision ID: public_sharing_001
Revises: g2h3i4j5k6l7
Create Date: 2025-06-27 00:00:00.000000

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "public_sharing_001"
down_revision: str | None = "g2h3i4j5k6l7"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "adventures", sa.Column("is_public", sa.Boolean(), nullable=False, server_default="0")
    )
    op.add_column("adventures", sa.Column("share_token", sa.String(length=36), nullable=True))
    op.add_column("adventures", sa.Column("shared_at", sa.DateTime(), nullable=True))
    op.create_unique_constraint("uq_adventures_share_token", "adventures", ["share_token"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("uq_adventures_share_token", "adventures", type_="unique")
    op.drop_column("adventures", "shared_at")
    op.drop_column("adventures", "share_token")
    op.drop_column("adventures", "is_public")
    # ### end Alembic commands ###
