apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: microadventures-cert-selfsigned
  namespace: microadventures
spec:
  commonName: local-microadventures.aronhedl.com
  secretName: microadventures-tls-selfsigned
  dnsNames:
    - microadventures.aronhedl.com
    - local-microadventures.aronhedl.com
    - localhost
  issuerRef:
    kind: ClusterIssuer
    name: selfsigned-issuer
