{% if docker_username and docker_password %}
apiVersion: v1
kind: Secret
metadata:
  name: microadventures-docker-secret
  namespace: microadventures
type: kubernetes.io/dockerconfigjson
stringData:
  .dockerconfigjson: |
    {
      "auths": {
        "https://index.docker.io/v1/": {
          "username": "{{ docker_username }}",
          "password": "{{ docker_password }}",
          "email": "{{ docker_email }}",
          "auth": "{{ docker_auth }}"
        }
      }
    }
{% endif %}
