apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  # - cert-manager.yaml  # Installed via Taskfile
  - cluster-issuer.yaml
  - certificate-selfsigned.yaml
  - middleware.yaml
  - ingressroute-https-selfsigned.yaml
  - ingressroute-http-redirect.yaml
  # - traefik.yaml  # Installed via Taskfile
  - docker-registry-secret.yaml
  - microadventures-secrets.yaml