apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: microadventures
  labels:
    app: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: hedlaron/microadventures-backend:foobarbaz
          imagePullPolicy: Always
          env:
            # Application configuration (from backend ConfigMap)
            - name: PORT
              valueFrom:
                configMapKeyRef:
                  name: backend-config
                  key: PORT
            - name: DOMAIN
              valueFrom:
                configMapKeyRef:
                  name: backend-config
                  key: DOMAIN
            - name: ENVIRONMENT
              valueFrom:
                configMapKeyRef:
                  name: backend-config
                  key: ENVIRONMENT
            - name: BACKEND_CORS_ORIGINS
              valueFrom:
                configMapKeyRef:
                  name: backend-config
                  key: BACKEND_CORS_ORIGINS
            # PostgreSQL connection (from GCP secrets for sensitive data)
            - name: POSTGRESQL_USERNAME
              valueFrom:
                secretKeyRef:
                  name: microadventures-gcp-secrets
                  key: POSTGRES_USER
            - name: POSTGRESQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: microadventures-gcp-secrets
                  key: POSTGRES_PASSWORD
            # PostgreSQL connection (from backend ConfigMap for non-sensitive data)
            - name: POSTGRESQL_SERVER
              valueFrom:
                configMapKeyRef:
                  name: backend-config
                  key: POSTGRESQL_SERVER
            - name: POSTGRESQL_PORT
              valueFrom:
                configMapKeyRef:
                  name: backend-config
                  key: POSTGRESQL_PORT
            - name: POSTGRESQL_DATABASE
              valueFrom:
                configMapKeyRef:
                  name: backend-config
                  key: POSTGRESQL_DATABASE
            # Secrets (from GCP secrets)
            - name: JWT_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: microadventures-gcp-secrets
                  key: JWT_SECRET_KEY
            - name: OPENAI_API_KEY
              valueFrom:
                secretKeyRef:
                  name: microadventures-gcp-secrets
                  key: OPENAI_API_KEY
            # Database URL (from GCP secrets)
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: microadventures-gcp-secrets
                  key: DATABASE_URL
          ports:
            - containerPort: 8000
              protocol: TCP
          readinessProbe:
            httpGet:
              path: /health
              port: 8000
          resources:
            limits:
              memory: "512Mi"
            requests:
              memory: "256Mi"
              cpu: "100m"
          securityContext:
            allowPrivilegeEscalation: false
            privileged: false
      imagePullSecrets:
        - name: dockerconfigjson
      securityContext:
        seccompProfile:
          type: RuntimeDefault