version: 3

tasks:
  01-install-trivy-operator:
    desc: "Install trivy operator into trivy-system namespace"
    cmds:
      - helm repo add aqua https://aquasecurity.github.io/helm-charts/
      - helm repo update
      - |
        helm upgrade --install trivy-operator aqua/trivy-operator \
          --namespace trivy-system \
          --create-namespace \
          --version 0.29.1

  02-uninstall-trivy-operator:
    desc: "Uninstall the trivy operator"
    cmds:
      - helm uninstall trivy-operator --namespace trivy-system

  03-check-trivy-operator-status:
    desc: "Check the status of the trivy operator"
    cmds:
      - kubectl get pods -n trivy-system

  04-get-trivy-vulnebility-report:
    desc: "Get the vulnerability report from trivy operator"
    cmds:
      - kubectl get vulnerabilityreports.aquasecurity.github.io -A -o wide

  05-get-trivy-microadventures-vulnerability-report:
    desc: "Get the vulnerability report for microadventures namespace"
    cmds:
      - kubectl get vulnerabilityreports.aquasecurity.github.io -n microadventures -o wide
      # to get a specific report, use:
      # kubectl get vulnerabilityreports.aquasecurity.github.io -n microadventures <NAME> -o yaml | yq
  